version: '3.9'

name: chat-bot_postgres

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sql
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql